CREATE TABLE quote_templates (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  category TEXT NOT NULL,
  emoji TEXT NOT NULL DEFAULT '📋',
  sortOrder INTEGER NOT NULL DEFAULT 0,
  itemsJson TEXT NOT NULL,
  isActive INTEGER NOT NULL DEFAULT 1,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
